set -g mouse on
set -g allow-passthrough on
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"
set -g focus-events on
set -g status-position top
set -g base-index 1
setw -g pane-base-index 1

# keep colors
set -g status-style bg=colour234,fg=white

# no left or right sections
set -g status-left ""
set -g status-right ""

# clean tab list only
setw -g window-status-separator ""
setw -g window-status-format ' #[fg=colour244,bg=colour234]#I:#W '
setw -g window-status-current-format '#[fg=colour234,bg=colour39]#[fg=colour234,bg=colour39,bold] #I:#W #[fg=colour39,bg=colour234,nobold]'
